#!/bin/bash

dirName=`dirname $0`
relativeDir=..

rootDir=$dirName/../../cilia-repo
ciliaDir=$rootDir/Cilia

# sauvegarde du directory courant
pushd .

# Suppression du repo
/bin/rm -fR $rootDir
mkdir $rootDir
cd $rootDir

# Téléchargement du repo et switch sur la branche
git clone https://github.com/torito/Cilia.git
cd Cilia
git checkout developpment

# Compilation
mvn clean install

# Copie des artefacts
cp ./src/admin/target/cilia-admin-1.2.2-SNAPSHOT.jar ..
cp ./src/runtime/target/cilia-runtime-1.2.2-SNAPSHOT.jar ..
cp ./src/core/target/cilia-core-1.2.2-SNAPSHOT.jar ..

# restauration du directory
popd

